# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2020 PHYTEC Messtechnik GmbH
# Author: Teresa Remmet <t.remmet@phytec.de>

ifdef CONFIG_SPL_BUILD
# necessary to create built-in.o
obj- := __dummy__.o
endif

obj-y += imx8m_som_detection.o
